USE exocube_db;

-- 1. Crear la tabla de testimonios y valoraciones de la tienda si no existe
CREATE TABLE IF NOT EXISTS testimonios (
    id_testimonio INT AUTO_INCREMENT,
    nombre_cliente VARCHAR(100) NOT NULL,
    comentario TEXT NOT NULL,
    calificacion INT NOT NULL DEFAULT 5, -- Rango del 1 al 5 (Estrellas)
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_testimonio)
) ENGINE=InnoDB;

-- 2. Inserción de 18 comentarios realistas para testear la paginación de 9 en 9
INSERT INTO testimonios (nombre_cliente, comentario, calificacion) VALUES 
('MARÍA ELENA VALDIVIA', '¡ME ENCANTA ESTA TIENDA! COMPRÉ LA MUÑECA BRATZ PARA EL CUMPLEAÑOS DE MI HIJA Y LLEGÓ CON UNA ENVOLTURA HERMOSA. EXCELENTE ATENCIÓN EN TACNA.', 5),
('JUAN CARLOS FLORES', 'LOS IMANES DE NEODIMIO SON SÚPER POTENTES. PERFECTOS PARA EL PROYECTO DE CIENCIAS DE MI HIJO. EL ENVÍO LLEGÓ SÚPER RÁPIDO.', 5),
('GABRIELA CONDORI', 'EXCELENTE TRATO EN LA TIENDA FÍSICA. SELECCIONÉ RECOJO EN TIENDA DE LA PELOTA DE FÚTBOL Y YA LA TENÍAN LISTA Y EMPACADA CUANDO LLEGUÉ.', 5),
('ROBERTO QUISPE', 'COMPRÉ LOS AUDÍFONOS GAMER PARA MI SOBRINO. TIENEN UN EXCELENTE SONIDO Y LAS LUCES LED LE ENCANTARON. MUY RECOMENDADO.', 4),
('LUCÍA APERESTEGUI', 'EL FRASCO DE BURBUJAS ES DE BUENA CALIDAD. EL JABÓN HACE BURBUJAS GIGANTES Y ES MUY DIVERTIDO. COMPRARÉ MÁS.', 5),
('CARLOS MIRANDA', 'BUENOS PRECIOS Y GRAN VARIEDAD DE JUGUETES IMPORTADOS. ME HUBIERA GUSTADO ENCONTRAR MÁS LEGOS DE STAR WARS EN STOCK, PERO EL QUE COMPRÉ ESTÁ GENIAL.', 4),
('PATRICIA MAMANI', 'EL VENTILADOR PORTÁTIL ES SÚPER ÚTIL PARA EL ESCRITORIO. TIENE TRES VELOCIDADES SILENCIOSAS Y ES RECARGABLE.', 5),
('RICARDO JORGE', 'COMPRÉ EL ARDUINO UNO PARA MIS CLASES DE ELECTRÓNICA. ESTÁ TOTALMENTE ORIGINAL Y FUNCIONA SIN PROBLEMAS. VOLVERÉ A COMPRAR.', 5),
('STEFANY CASAS', 'LA ATENCIÓN POR WHATSAPP ES MUY AMABLE. ME ASESORARON SOBRE QUÉ REGALO ERA ADECUADO PARA UN NIÑO DE 6 AÑOS. EXCELENTES.', 5),
('FERNANDO VILLANUEVA', 'EL BALDE DE CUBOS DIDÁCTICOS ES MUY ENTRETENIDO PARA MI BEBÉ. LA CAJA ES RESISTENTE Y SIRVE PARA GUARDARLOS.', 4),
('VANESSA CALIZAYA', 'EL TERMO TRANSPARENTE ES GRANDE Y SÚPER ÚTIL. NO DERRAMA NADA DE AGUA Y TIENE UNA ESCALA PARA CONTROLAR LO QUE TOMO.', 5),
('ALEJANDRO PINTO', 'COMPRÉ EL SET DE CARRITOS METÁLICOS. SON MUY RESISTENTES A LOS GOLPES DE MI HIJO MENOR. BUENA CALIDAD DE METAL.', 5),
('MÓNICA SUÁREZ', 'LA CAJA DE LAPICEROS VIKINGO TIENE UNA ESCRITURA SÚPER SUAVE. PERFECTA PARA MIS APUNTES. VOLVERÉ A COMPRAR MÁS PRODUCTOS.', 4),
('CHRISTIAN ORTIZ', 'EL SERVOMOTOR ES COMPATIBLE CON ARDUINO. LLEGÓ SÚPER RÁPIDO A MI CASA. MUY BUEN TRATO.', 5),
('ELIZABETH RAMOS', 'LAS PELOTITAS DE GOMA SON MUY DIVERTIDAS. REBOTAN SÚPER ALTO. BUENA ATENCIÓN EN LA TIENDA.', 5),
('HÉCTOR COAQUIRA', 'EL PUNTERO LÁSER TIENE UN HAZ DE LUZ MUY POTENTE. COMPLETO CON SU CARGADOR DE BATERÍA. BUENA EXPERIENCIA DE COMPRA.', 4),
('KARINA ROSAS', 'COMPRÉ EL KIT DE HERRAMIENTAS LEGO. ES UN POCO COMPLICADO DE USAR AL PRINCIPIO, PERO AYUDA MUCHO A DESARMAR LAS PIEZAS.', 4),
('ÁNGEL GÓMEZ', 'EXCELENTE VARIEDAD DE REGALOS MINORISTAS EN TACNA. SE VALORA MUCHO QUE SE PUEDA PAGAR POR YAPE.', 5);